# -*- coding: utf-8 -*-
"""dlfa1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AwfcS9xBpbUvICs5PrM7nCAIoC8yHQBq
"""

!pip install torchview torchviz
# !pip install tensorboardcolab
!pip install -U 'git+https://github.com/facebookresearch/fvcore' #
!pip install ptflops # for FLOPs and MACs calculation.

#Basic libraries
import os
import numpy as np
import copy
import random
import matplotlib.pyplot as plt


#Framework
import torch
import torchvision

#data and its management related libraries
from torch.utils.data import Dataset, DataLoader
from torchvision import datasets, models, transforms
import torchvision.transforms as transforms
from torch.utils.tensorboard import SummaryWriter
import torchview #Visualizes the model architecture
from torchviz import make_dot # Visualizes the computation graph, how operations connect, how gradients flow.


from PIL import Image #python imaging library, image handling
# PIL.Image - load images, convert formats, apply basic image operations
import cv2 # OpenCV- image transformations, filtering



#for creating neural networks
import torch.nn as nn # Contains- layers (Linear, Conv2d, etc.)
import torch.nn.functional as F #Provides functional versions of operations: ReLU, softmax, pooling
import torchvision.transforms.functional as TF # Functional image transformations

#for optimising neural networks
import torch.optim as optim

#for metrics and analysis
import sklearn
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
from torchsummary import summary # Prints a layer-by-layer summary of the model - number of parameters, input/output shapes


#For Computing FLOPs and MACs
import fvcore
from fvcore.nn import FlopCountAnalysis # for FLOPs calculations
from fvcore.nn import flop_count_table # for FLOPs calculations
from ptflops import get_model_complexity_info #another lib for FLOPs and MACs calculation.

"""<h1>Question 1: Loading the Dataset and splitting</h1>"""

pip install ucimlrepo

from ucimlrepo import fetch_ucirepo

# fetch dataset
parkinsons_telemonitoring = fetch_ucirepo(id=189)

# data (as pandas dataframes)
X = parkinsons_telemonitoring.data.features
y = parkinsons_telemonitoring.data.targets

# metadata
print(parkinsons_telemonitoring.metadata)

# variable information
print(parkinsons_telemonitoring.variables)

X.shape

y

from sklearn.model_selection import train_test_split
X_dash, X_test, y_dash, y_test = train_test_split(X,y,test_size=0.15,random_state=42)

#15/85 = 0.17647

X_train, X_val, y_train, y_val = train_test_split(X_dash,y_dash,test_size=0.17647,random_state=42)

"""<h1>Question 2: Feature Scaling and PyTorch DataLoaders"""

#Standard Scaler is used as ReLU activation function will be used

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_val= scaler.transform(X_val)
X_test= scaler.transform(X_test)

#converting sets to tensors

X_train = torch.tensor(X_train,dtype=torch.float32)
X_val = torch.tensor(X_val,dtype=torch.float32)
X_test = torch.tensor(X_test,dtype=torch.float32)

y_train = torch.tensor(y_train.values,dtype=torch.float32)
y_val = torch.tensor(y_val.values,dtype=torch.float32)
y_test = torch.tensor(y_test.values,dtype=torch.float32)

from torch.utils.data import TensorDataset

train_ds = TensorDataset(X_train, y_train)
val_ds = TensorDataset(X_val, y_val)
test_ds = TensorDataset(X_test, y_test)

x = 32 #batch_size

train_loader = DataLoader(train_ds, batch_size=x, shuffle=True)
val_loader = DataLoader(val_ds, batch_size=x, shuffle=False)
test_loader = DataLoader(test_ds, batch_size=x, shuffle=False)

"""<h1>Question 3: Designing Neural Network</h1>

The activation function for the output layer must be linear as for regression, we require the output to be in complete range and not restricted.
"""

class RegressionNN(nn.Module):
    def __init__(self, input_dim, hidden_layers):
        super().__init__()

        layers = []
        prev_dim = input_dim

        for h in hidden_layers:
            layers.append(nn.Linear(prev_dim, h))
            layers.append(nn.ReLU())
            prev_dim = h

        layers.append(nn.Linear(prev_dim, 2))  # 2 target variables & linear activation

        self.model = nn.Sequential(*layers)

    def forward(self, x):
        return self.model(x)

def evaluate_model(hidden_layers, train_loader, val_loader, input_dim, epochs=20, lr=0.01):

    model = RegressionNN(input_dim, hidden_layers)
    criterion = nn.MSELoss()
    optimizer = torch.optim.Adam(model.parameters(), lr)

    # Train for a few epochs (ONLY for architecture comparison)
    for _ in range(epochs):
        model.train()
        for x, y in train_loader:
            optimizer.zero_grad()
            outputs = model(x)
            loss = criterion(outputs, y)
            loss.backward()
            optimizer.step()

    # Compute validation loss
    model.eval()
    val_loss = 0.0
    with torch.no_grad():
        for x, y in val_loader:
            outputs = model(x)
            loss = criterion(outputs, y)
            val_loss += loss.item()

    val_loss /= len(val_loader)
    return val_loss

input_dim = X_train.shape[1]
#input_dim

#different hidden layer configurations
architectures = {
    "Single hidden layer (32)": [32],
    "Single hidden layer (64)": [64],
    "Single hidden layer (128)": [128],
    "Two hidden layers (128, 64)": [128, 64],
    "Two hidden layers (64, 64)": [64, 64],
    "Two hidden layers (128, 128)": [128, 128],
    "Three hidden layers (256, 128, 64)": [256, 128, 64],
    "Three hidden layers (128, 64, 32)": [128, 64, 32],
    "Rule of Thumb Heuristic": [input_dim*4,input_dim*2,input_dim],
    "Three hidden layers (512, 256, 128)": [128, 64, 32]
}

validation_losses = {}

for name, hidden_layers in architectures.items():
    loss = evaluate_model(
        hidden_layers,
        train_loader,
        val_loader,
        input_dim
    )
    validation_losses[name] = loss
    print(f"{name} → Validation Loss: {loss:.4f}")

"""On evaluation of multiple architectures, and comparision of validation loss, it is clearly found that the hidden later configuration of **Three Hidden layers: [256,128,64]** gives the least validation loss. Hence, this configuration is selected for the final model."""

best_architecture = min(validation_losses, key=validation_losses.get)
print("Selected architecture based on validation loss:", best_architecture)

best_hidden_layers = architectures[best_architecture]

#Loading the final model
finalModel = RegressionNN(input_dim, best_hidden_layers)

"""<h1>Question 4: Model Summary and FLOPs</h1>"""

#Model Summary and number of trainable parameters
print(finalModel)

total_params = sum(p.numel() for p in finalModel.parameters() if p.requires_grad)
print("Total number of trainable parameters:", total_params)

summary(finalModel, (1,input_dim))

#computing flops
random_tensor=torch.randn(1,input_dim)
flops = FlopCountAnalysis(finalModel, random_tensor)

print('Total FLOPs',flops.total()) # total number of floating-point operations required for one forward pass

print('FLOPs by Operator',flops.by_operator()) # which types of operations are contributing most to the computation.

print('FLOPs by Module',flops.by_module()) # breaks FLOPs down layer by layer.

print('FLOPs by Module and Operator',flops.by_module_and_operator()) # combines: Which layer + Which operation + How many FLOPs

print(flop_count_table(flops))

#Visualizing the Network
torchview.draw_graph(finalModel, input_size=(1,input_dim), graph_name="SimpleNN", save_graph=True)
plt.figure(figsize=(5, 10))
plt.imshow(plt.imread('SimpleNN.gv.png'))

"""Mean Squared Error (MSE) loss is appropriate for this task since the problem involves predicting continuous target variables. MSE penalizes larger prediction errors more strongly and provides a smooth gradient that is well-suited for regression problems."""

loss_function = nn.MSELoss()

"""<h1>Question 5: Training using SGD</h1>"""

optimizer = torch.optim.SGD(
    finalModel.parameters(),
    lr=0.0001,
    momentum=0.9
)

#if the validation loss doesnt improve in 5 epochs, then learning rate is reduced by half
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer,
    mode='min',
    patience=5,
    factor=0.5,
)

total_epochs = 100
train_losses = []
val_losses = []

best_val_loss = float('inf') #initializing validation loss to infinity

for epoch in range(total_epochs):

    # ---- Training phase ----
    finalModel.train()
    running_train_loss = 0.0

    for x, y in train_loader:
        # x = x.float()
        # y = y.float()

        optimizer.zero_grad()
        outputs = finalModel(x)
        loss = loss_function(outputs, y)
        loss.backward()
        optimizer.step()

        running_train_loss += loss.item()

    train_loss = running_train_loss / len(train_loader)
    train_losses.append(train_loss)


    # ---- Validation phase ----
    finalModel.eval()
    running_val_loss = 0.0

    with torch.no_grad():
        for x, y in val_loader:
            # x = x.float()
            # y = y.float()

            outputs = finalModel(x)
            loss = loss_function(outputs, y)
            running_val_loss += loss.item()

    val_loss = running_val_loss / len(val_loader)
    val_losses.append(val_loss)


    # ---- Scheduler step ----
    scheduler.step(val_loss)


    # ---- Save best model (needed for Q6) ----
    if val_loss < best_val_loss:
        best_val_loss = val_loss
        torch.save(finalModel.state_dict(), "best_model.pth")


    print(
        f"Epoch [{epoch+1}/{total_epochs}] | "
        f"Train Loss: {train_loss:.4f} | "
        f"Val Loss: {val_loss:.4f}"
    )

plt.figure()
plt.plot(train_losses, label="Training Loss")
plt.plot(val_losses, label="Validation Loss")
plt.xlabel("Epochs")
plt.ylabel("MSE Loss")
plt.title("Training and Validation Loss vs Epochs")
plt.legend()
plt.show()

"""<h1>Question 6: Best Model and Test Prediction</h1>


"""

best_model = RegressionNN(
    input_dim=X_train.shape[1],
    hidden_layers=[256,128,64]
)

#This best model is saved in question 5 training loop and loaded here
best_model.load_state_dict(torch.load("best_model.pth"))
best_model.eval()

y_test_true = []
y_test_pred = []

with torch.no_grad():
    for x, y in test_loader:
        outputs = best_model(x)

        y_test_true.append(y)
        y_test_pred.append(outputs)

print(y_test_true[0].shape)

#combining data batches
y_test_true = torch.cat(y_test_true)
y_test_pred = torch.cat(y_test_pred)

print(y_test_true.shape)

"""<h1>Question 7: Analyzing Model Performance</h1>"""

best_model.eval()

y_train_true = []
y_train_pred = []

with torch.no_grad():
    for x, y in train_loader:
        x = x.float()
        y = y.float()

        outputs = best_model(x)

        y_train_true.append(y)
        y_train_pred.append(outputs)

y_train_true = torch.cat(y_train_true).cpu().numpy()
y_train_pred = torch.cat(y_train_pred).cpu().numpy()

plt.figure()
plt.scatter(y_train_true[:, 0], y_train_pred[:, 0], alpha=0.5)
plt.xlabel("Ground Truth: motor_UPDRS")
plt.ylabel("Predicted: motor_UPDRS")
plt.title("Prediction vs Ground Truth (motor_UPDRS) – Training Set")
plt.show()

plt.figure()
plt.scatter(y_train_true[:, 1], y_train_pred[:, 1], alpha=0.5)
plt.xlabel("Ground Truth: total_UPDRS")
plt.ylabel("Predicted: total_UPDRS")
plt.title("Prediction vs Ground Truth (total_UPDRS) – Training Set")
plt.show()

from sklearn.metrics import r2_score
r2_motor = r2_score(y_test_true[:, 0], y_test_pred[:, 0])
r2_total = r2_score(y_test_true[:, 1], y_test_pred[:, 1])

print("R² score on test set (motor_UPDRS):", r2_motor)
print("R² score on test set (total_UPDRS):", r2_total)